name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Auto Minify
        uses: nizarmah/auto-minify@master
        with:
          directory: 'src'
          output: 'dist'

      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action
        with:
          repository: 'dist'
          commit_message: "Github Action: Auto Minified JS and CSS files"
          branch: ${{ github.ref }}
