name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4

      - name:  Clean
        run: |
          rm dist/css/*

      - name:  Install dev dependancies
        run: |
          sudo npm install -g sass rtlcss  postcss postcss-cli autoprefixer

      - name: Compile CSS
        run:
          sass scss:dist/css

      - name: Right to left CSS
        run: |
          rtlcss -d dist/*

      - name: Minify
        uses: nizarmah/auto-minify@master
        with:
          directory: 'dist'

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Dist
